language: node_js
node_js:
- lts/*
before_install:
- npm install -g npm
- npm install -g grunt-cli
notifications:
  email:
    on_success: change
    on_failure: change
sudo: required
cache:
  directories:
  - node_modules
addons:
  chrome: stable
deploy:
  provider: npm
  email: stdavis@utah.gov
  api_key:
    secure: QNHVVd1CWdSZzipd/D5DNW+gdiS3c0YdEGylb5LfBF39elgVjXdEjHGv9nSPazsvz1OI7byeX8+SUhZNCBaM3X8dNiI1Ld+gKZn93O1dDa6O1SnWH8kaRfrqzJD50cvU2deHUEBERxiJExZvgXigmc4K1REvWCwz11ORB7iiD/g3o3hqLmEpon9+ze1IePuUYDbqhBdovZrLH4dxTay4b4QXOsRWE6SeoryB1E5wdihoDcGMDIHhRn2sxeWH5GatG2TA5VonPHmr3uxFc6/ccT50kLl5Hu6FnIbrf/eKKDgyGPqVYTgBbVCgTOKu5l290A0qk8xuL9AsG71//Ux3jimF9tvCv/3SVQlvP0dsRp6VmOQ1N34LQdqSs9wyvycQ5zYeKW7EYg63LTSzOEkDlZH+4fiM0PBzJj7SZeoeQd/Y6M5s+xg9jwKNkFqo+hOt3VMP15QAiO8xMJW6o4HcXVHrGEamAduXUDXPnHKpGsIeDsEFaANhF5I2oV/uSI6iii2cg1X8tFuWWnBwOIrPP9967GSpX3rj5QjWkwYUwXuYB0qmm2fRkfg3ZHemY7jcTsgBxFRoodlJwPikJ9WEV39EAGLS9OnE593ZDLk9I7/bPmxDI8GAAIn7r7wDOIWiys+DCa174t1BAvIRmBs7+XgHwLzajjeCIRS8EpikCFM=
  on:
    tags: true
    repo: agrc-widgets/helpers
